// This file is auto-generated by @hey-api/openapi-ts

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

/**
 * Response after successful login with user data
 */
export type LoginResponse = {
    access_token: string;
    token_type?: string;
    user: UserPublicWithRelations;
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type OrganizationPublic = {
    name: string;
    slug: string;
    description?: (string | null);
    logo_url?: (string | null);
    is_active?: boolean;
    id: string;
    created_at: string;
    updated_at: string;
};

/**
 * Schema for creating a new organization with admin user
 */
export type OrganizationSignup = {
    organization_name: string;
    organization_slug: string;
    organization_description?: (string | null);
    admin_email: string;
    admin_password: string;
    admin_first_name: string;
    admin_last_name: string;
    admin_phone?: (string | null);
};

export type OrganizationUpdate = {
    name?: (string | null);
    description?: (string | null);
    logo_url?: (string | null);
    is_active?: (boolean | null);
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type RolePublic = {
    name: string;
    description?: (string | null);
    permissions?: Array<(string)>;
    id: number;
    created_at: string;
};

export type RolesPublic = {
    data: Array<RolePublic>;
    count: number;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    password: string;
    first_name: string;
    last_name: string;
    phone?: (string | null);
    role_id: number;
};

export type UserPublic = {
    email: string;
    first_name: string;
    last_name: string;
    phone?: (string | null);
    avatar_url?: (string | null);
    is_active?: boolean;
    is_verified?: boolean;
    id: string;
    organization_id: string;
    role_id: number;
    last_login_at?: (string | null);
    created_at: string;
    updated_at: string;
};

/**
 * User with organization and role included
 */
export type UserPublicWithRelations = {
    email: string;
    first_name: string;
    last_name: string;
    phone?: (string | null);
    avatar_url?: (string | null);
    is_active?: boolean;
    is_verified?: boolean;
    id: string;
    organization_id: string;
    role_id: number;
    last_login_at?: (string | null);
    created_at: string;
    updated_at: string;
    organization: OrganizationPublic;
    role: RolePublic;
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    first_name?: (string | null);
    last_name?: (string | null);
    phone?: (string | null);
    avatar_url?: (string | null);
    is_active?: (boolean | null);
    role_id?: (number | null);
};

export type UserUpdateMe = {
    first_name?: (string | null);
    last_name?: (string | null);
    email?: (string | null);
    phone?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (LoginResponse);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type OrganizationsSignupOrganizationData = {
    requestBody: OrganizationSignup;
};

export type OrganizationsSignupOrganizationResponse = (LoginResponse);

export type OrganizationsGetMyOrganizationResponse = (OrganizationPublic);

export type OrganizationsUpdateMyOrganizationData = {
    requestBody: OrganizationUpdate;
};

export type OrganizationsUpdateMyOrganizationResponse = (OrganizationPublic);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type RolesListRolesResponse = (RolesPublic);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);